//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileInfo", Namespace="http://tempuri.org/")]
    public partial class FileInfo : object
    {
        
        private byte[] FileArrayField;
        
        private int ClinicIDField;
        
        private int WebServerIDField;
        
        private string FileNameField;
        
        private string FileExtField;
        
        private string FileTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] FileArray
        {
            get
            {
                return this.FileArrayField;
            }
            set
            {
                this.FileArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ClinicID
        {
            get
            {
                return this.ClinicIDField;
            }
            set
            {
                this.ClinicIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int WebServerID
        {
            get
            {
                return this.WebServerIDField;
            }
            set
            {
                this.WebServerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FileExt
        {
            get
            {
                return this.FileExtField;
            }
            set
            {
                this.FileExtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultSet", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FileServiceReference.FileInfo))]
    public partial class ResultSet : object
    {
        
        private bool ResultField;
        
        private string DescriptionField;
        
        private object ResultObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object ResultObject
        {
            get
            {
                return this.ResultObjectField;
            }
            set
            {
                this.ResultObjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServiceReference.FileServiceSoap")]
    public interface FileServiceSoap
    {
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 file 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveImg", ReplyAction="*")]
        FileServiceReference.SaveImgResponse SaveImg(FileServiceReference.SaveImgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveImg", ReplyAction="*")]
        System.Threading.Tasks.Task<FileServiceReference.SaveImgResponse> SaveImgAsync(FileServiceReference.SaveImgRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 LoadImgResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadImg", ReplyAction="*")]
        FileServiceReference.LoadImgResponse LoadImg(FileServiceReference.LoadImgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadImg", ReplyAction="*")]
        System.Threading.Tasks.Task<FileServiceReference.LoadImgResponse> LoadImgAsync(FileServiceReference.LoadImgRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 DeleteImgResult 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteImg", ReplyAction="*")]
        FileServiceReference.DeleteImgResponse DeleteImg(FileServiceReference.DeleteImgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteImg", ReplyAction="*")]
        System.Threading.Tasks.Task<FileServiceReference.DeleteImgResponse> DeleteImgAsync(FileServiceReference.DeleteImgRequest request);
        
        // CODEGEN: 正在生成消息协定，因为命名空间 http://tempuri.org/ 的元素名称 path 未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestRedirect", ReplyAction="*")]
        FileServiceReference.TestRedirectResponse TestRedirect(FileServiceReference.TestRedirectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestRedirect", ReplyAction="*")]
        System.Threading.Tasks.Task<FileServiceReference.TestRedirectResponse> TestRedirectAsync(FileServiceReference.TestRedirectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveImgRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveImg", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.SaveImgRequestBody Body;
        
        public SaveImgRequest()
        {
        }
        
        public SaveImgRequest(FileServiceReference.SaveImgRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveImgRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FileServiceReference.FileInfo file;
        
        public SaveImgRequestBody()
        {
        }
        
        public SaveImgRequestBody(FileServiceReference.FileInfo file)
        {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveImgResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveImgResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.SaveImgResponseBody Body;
        
        public SaveImgResponse()
        {
        }
        
        public SaveImgResponse(FileServiceReference.SaveImgResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveImgResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FileServiceReference.ResultSet SaveImgResult;
        
        public SaveImgResponseBody()
        {
        }
        
        public SaveImgResponseBody(FileServiceReference.ResultSet SaveImgResult)
        {
            this.SaveImgResult = SaveImgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadImgRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadImg", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.LoadImgRequestBody Body;
        
        public LoadImgRequest()
        {
        }
        
        public LoadImgRequest(FileServiceReference.LoadImgRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadImgRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WebServerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FileID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ClinicID;
        
        public LoadImgRequestBody()
        {
        }
        
        public LoadImgRequestBody(int WebServerID, int FileID, int ClinicID)
        {
            this.WebServerID = WebServerID;
            this.FileID = FileID;
            this.ClinicID = ClinicID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadImgResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadImgResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.LoadImgResponseBody Body;
        
        public LoadImgResponse()
        {
        }
        
        public LoadImgResponse(FileServiceReference.LoadImgResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadImgResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FileServiceReference.ResultSet LoadImgResult;
        
        public LoadImgResponseBody()
        {
        }
        
        public LoadImgResponseBody(FileServiceReference.ResultSet LoadImgResult)
        {
            this.LoadImgResult = LoadImgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteImgRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteImg", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.DeleteImgRequestBody Body;
        
        public DeleteImgRequest()
        {
        }
        
        public DeleteImgRequest(FileServiceReference.DeleteImgRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteImgRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WebServerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int FileID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ClinicID;
        
        public DeleteImgRequestBody()
        {
        }
        
        public DeleteImgRequestBody(int WebServerID, int FileID, int ClinicID)
        {
            this.WebServerID = WebServerID;
            this.FileID = FileID;
            this.ClinicID = ClinicID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteImgResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteImgResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.DeleteImgResponseBody Body;
        
        public DeleteImgResponse()
        {
        }
        
        public DeleteImgResponse(FileServiceReference.DeleteImgResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteImgResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FileServiceReference.ResultSet DeleteImgResult;
        
        public DeleteImgResponseBody()
        {
        }
        
        public DeleteImgResponseBody(FileServiceReference.ResultSet DeleteImgResult)
        {
            this.DeleteImgResult = DeleteImgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRedirectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestRedirect", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.TestRedirectRequestBody Body;
        
        public TestRedirectRequest()
        {
        }
        
        public TestRedirectRequest(FileServiceReference.TestRedirectRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestRedirectRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WebServerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string path;
        
        public TestRedirectRequestBody()
        {
        }
        
        public TestRedirectRequestBody(int WebServerID, string path)
        {
            this.WebServerID = WebServerID;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRedirectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestRedirectResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileServiceReference.TestRedirectResponseBody Body;
        
        public TestRedirectResponse()
        {
        }
        
        public TestRedirectResponse(FileServiceReference.TestRedirectResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestRedirectResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] TestRedirectResult;
        
        public TestRedirectResponseBody()
        {
        }
        
        public TestRedirectResponseBody(byte[] TestRedirectResult)
        {
            this.TestRedirectResult = TestRedirectResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface FileServiceSoapChannel : FileServiceReference.FileServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FileServiceSoapClient : System.ServiceModel.ClientBase<FileServiceReference.FileServiceSoap>, FileServiceReference.FileServiceSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FileServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FileServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), FileServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FileServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FileServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileServiceReference.SaveImgResponse FileServiceReference.FileServiceSoap.SaveImg(FileServiceReference.SaveImgRequest request)
        {
            return base.Channel.SaveImg(request);
        }
        
        public FileServiceReference.ResultSet SaveImg(FileServiceReference.FileInfo file)
        {
            FileServiceReference.SaveImgRequest inValue = new FileServiceReference.SaveImgRequest();
            inValue.Body = new FileServiceReference.SaveImgRequestBody();
            inValue.Body.file = file;
            FileServiceReference.SaveImgResponse retVal = ((FileServiceReference.FileServiceSoap)(this)).SaveImg(inValue);
            return retVal.Body.SaveImgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileServiceReference.SaveImgResponse> FileServiceReference.FileServiceSoap.SaveImgAsync(FileServiceReference.SaveImgRequest request)
        {
            return base.Channel.SaveImgAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileServiceReference.SaveImgResponse> SaveImgAsync(FileServiceReference.FileInfo file)
        {
            FileServiceReference.SaveImgRequest inValue = new FileServiceReference.SaveImgRequest();
            inValue.Body = new FileServiceReference.SaveImgRequestBody();
            inValue.Body.file = file;
            return ((FileServiceReference.FileServiceSoap)(this)).SaveImgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileServiceReference.LoadImgResponse FileServiceReference.FileServiceSoap.LoadImg(FileServiceReference.LoadImgRequest request)
        {
            return base.Channel.LoadImg(request);
        }
        
        public FileServiceReference.ResultSet LoadImg(int WebServerID, int FileID, int ClinicID)
        {
            FileServiceReference.LoadImgRequest inValue = new FileServiceReference.LoadImgRequest();
            inValue.Body = new FileServiceReference.LoadImgRequestBody();
            inValue.Body.WebServerID = WebServerID;
            inValue.Body.FileID = FileID;
            inValue.Body.ClinicID = ClinicID;
            FileServiceReference.LoadImgResponse retVal = ((FileServiceReference.FileServiceSoap)(this)).LoadImg(inValue);
            return retVal.Body.LoadImgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileServiceReference.LoadImgResponse> FileServiceReference.FileServiceSoap.LoadImgAsync(FileServiceReference.LoadImgRequest request)
        {
            return base.Channel.LoadImgAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileServiceReference.LoadImgResponse> LoadImgAsync(int WebServerID, int FileID, int ClinicID)
        {
            FileServiceReference.LoadImgRequest inValue = new FileServiceReference.LoadImgRequest();
            inValue.Body = new FileServiceReference.LoadImgRequestBody();
            inValue.Body.WebServerID = WebServerID;
            inValue.Body.FileID = FileID;
            inValue.Body.ClinicID = ClinicID;
            return ((FileServiceReference.FileServiceSoap)(this)).LoadImgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileServiceReference.DeleteImgResponse FileServiceReference.FileServiceSoap.DeleteImg(FileServiceReference.DeleteImgRequest request)
        {
            return base.Channel.DeleteImg(request);
        }
        
        public FileServiceReference.ResultSet DeleteImg(int WebServerID, int FileID, int ClinicID)
        {
            FileServiceReference.DeleteImgRequest inValue = new FileServiceReference.DeleteImgRequest();
            inValue.Body = new FileServiceReference.DeleteImgRequestBody();
            inValue.Body.WebServerID = WebServerID;
            inValue.Body.FileID = FileID;
            inValue.Body.ClinicID = ClinicID;
            FileServiceReference.DeleteImgResponse retVal = ((FileServiceReference.FileServiceSoap)(this)).DeleteImg(inValue);
            return retVal.Body.DeleteImgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileServiceReference.DeleteImgResponse> FileServiceReference.FileServiceSoap.DeleteImgAsync(FileServiceReference.DeleteImgRequest request)
        {
            return base.Channel.DeleteImgAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileServiceReference.DeleteImgResponse> DeleteImgAsync(int WebServerID, int FileID, int ClinicID)
        {
            FileServiceReference.DeleteImgRequest inValue = new FileServiceReference.DeleteImgRequest();
            inValue.Body = new FileServiceReference.DeleteImgRequestBody();
            inValue.Body.WebServerID = WebServerID;
            inValue.Body.FileID = FileID;
            inValue.Body.ClinicID = ClinicID;
            return ((FileServiceReference.FileServiceSoap)(this)).DeleteImgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileServiceReference.TestRedirectResponse FileServiceReference.FileServiceSoap.TestRedirect(FileServiceReference.TestRedirectRequest request)
        {
            return base.Channel.TestRedirect(request);
        }
        
        public byte[] TestRedirect(int WebServerID, string path)
        {
            FileServiceReference.TestRedirectRequest inValue = new FileServiceReference.TestRedirectRequest();
            inValue.Body = new FileServiceReference.TestRedirectRequestBody();
            inValue.Body.WebServerID = WebServerID;
            inValue.Body.path = path;
            FileServiceReference.TestRedirectResponse retVal = ((FileServiceReference.FileServiceSoap)(this)).TestRedirect(inValue);
            return retVal.Body.TestRedirectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileServiceReference.TestRedirectResponse> FileServiceReference.FileServiceSoap.TestRedirectAsync(FileServiceReference.TestRedirectRequest request)
        {
            return base.Channel.TestRedirectAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileServiceReference.TestRedirectResponse> TestRedirectAsync(int WebServerID, string path)
        {
            FileServiceReference.TestRedirectRequest inValue = new FileServiceReference.TestRedirectRequest();
            inValue.Body = new FileServiceReference.TestRedirectRequestBody();
            inValue.Body.WebServerID = WebServerID;
            inValue.Body.path = path;
            return ((FileServiceReference.FileServiceSoap)(this)).TestRedirectAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FileServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FileServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FileServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ec2-3-88-124-242.compute-1.amazonaws.com/MdlandFileService/FileService.asm" +
                        "x");
            }
            if ((endpointConfiguration == EndpointConfiguration.FileServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ec2-3-88-124-242.compute-1.amazonaws.com/MdlandFileService/FileService.asm" +
                        "x");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FileServiceSoap,
            
            FileServiceSoap12,
        }
    }
}
